input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["orders", "deliveries", "riders", "restaurants", "payments", "anomalies", "actions"]
    codec => json
    group_id => "logstash-consumer-v2"
    auto_offset_reset => "earliest"
    decorate_events => "basic"
  }
}

filter {
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }

  # Kafka 토픽명을 일반 필드로 복사
  mutate {
    add_field => { "kafka_topic" => "%{[@metadata][kafka][topic]}" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ordersense-%{kafka_topic}-%{+YYYY.MM}"
  }
}